version: '3'
services:
  mailer-server:
    container_name: mailer-server
    build: 
      context: ./
      dockerfile: mailer/Dockerfile
    volumes:
      - ./mailer:/app/mailer
      - ./protos:/app/protos
    ports:
      - '50001:50001'
    networks:
      - grpc-network
  apigateway:
    container_name: apigateway
    build: 
      context: ./
      dockerfile: apigateway/Dockerfile
    volumes:
      - ./apigateway:/app/apigateway
      - ./protos:/app/protos
    ports:
      - '8080:8080'
    environment:
      MAILER_ENDPOINT: mailer-server
      PORT: 8080
    networks:
      - grpc-network
networks:
  grpc-network:
    driver: bridge
