version: '3'
services:
  mailer-server:
    container_name: mailer-server
    build: 
      context: ./mailer
      dockerfile: Dockerfile
    volumes:
      - ./mailer:/app
    ports:
      - '50001:50001'
    networks:
      - grpc-network
  api-server:
    container_name: api-server
    build: 
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/app
    ports:
      - '8080:8080'
    environment:
      MAILER_ENDPOINT: mailer-server:50001
      PORT: 8080
    networks:
      - grpc-network
networks:
  grpc-network:
    driver: bridge
